import Memory from '../../Memory/Memory';
import { Byte, Word } from '../../Types';

export default {
  map: {
    0x00: function () {},
    0x01: function () {
      this.R.BC.set(Memory.readWord(this.PC.value()));
      this.PC.set(this.PC.value() + 2);
    },
    0x02: function () {
      Memory.writeByte(this.R.BC.value(), this.R.AF.upper());
    },
    0x03: function () {
      this.R.BC.set(this.R.BC.value() + 1);
    },
    0x04: function () {
      // convert operand to unsigned
      const operand = new Byte(1);
      // check for half carry on affected byte only
      this.checkHalfCarry(this.R.BC.upper(), operand);
      // perform addition
      operand.set(this.R.BC.upper().value() + operand.value());
      this.R.BC.setUpper(operand);

      this.checkZFlag(this.R.BC.upper());
      this.R.F.N = false;
    },
    0x05: function () {
      // convert operand to unsigned
      const operand = new Byte(-1);
      this.checkHalfCarry(this.R.BC.upper(), operand);
      operand.set(this.R.BC.upper().value() + operand.value());
      this.R.BC.setUpper(operand);

      this.checkZFlag(this.R.BC.upper());
      this.R.F.N = true;
    },
    6: function () {},
    7: function () {},
    8: function () {},
    9: function () {},
    10: function () {},
    11: function () {},
    12: function () {},
    13: function () {},
    14: function () {},
    15: function () {},
    16: function () {},
    17: function () {},
    18: function () {},
    19: function () {},
    20: function () {},
    21: function () {},
    22: function () {},
    23: function () {},
    24: function () {},
    25: function () {},
    26: function () {},
    27: function () {},
    28: function () {},
    29: function () {},
    30: function () {},
    31: function () {},
    32: function () {},
    33: function () {},
    34: function () {},
    35: function () {},
    36: function () {},
    37: function () {},
    38: function () {},
    39: function () {},
    40: function () {},
    41: function () {},
    42: function () {},
    43: function () {},
    44: function () {},
    45: function () {},
    46: function () {},
    47: function () {},
    48: function () {},
    49: function () {},
    50: function () {},
    51: function () {},
    52: function () {},
    53: function () {},
    54: function () {},
    55: function () {},
    56: function () {},
    57: function () {},
    58: function () {},
    59: function () {},
    60: function () {},
    61: function () {},
    62: function () {},
    63: function () {},
    64: function () {},
    65: function () {},
    66: function () {},
    67: function () {},
    68: function () {},
    69: function () {},
    70: function () {},
    71: function () {},
    72: function () {},
    73: function () {},
    74: function () {},
    75: function () {},
    76: function () {},
    77: function () {},
    78: function () {},
    79: function () {},
    80: function () {},
    81: function () {},
    82: function () {},
    83: function () {},
    84: function () {},
    85: function () {},
    86: function () {},
    87: function () {},
    88: function () {},
    89: function () {},
    90: function () {},
    91: function () {},
    92: function () {},
    93: function () {},
    94: function () {},
    95: function () {},
    96: function () {},
    97: function () {},
    98: function () {},
    99: function () {},
    100: function () {},
    101: function () {},
    102: function () {},
    103: function () {},
    104: function () {},
    105: function () {},
    106: function () {},
    107: function () {},
    108: function () {},
    109: function () {},
    110: function () {},
    111: function () {},
    112: function () {},
    113: function () {},
    114: function () {},
    115: function () {},
    116: function () {},
    117: function () {},
    118: function () {},
    119: function () {},
    120: function () {},
    121: function () {},
    122: function () {},
    123: function () {},
    124: function () {},
    125: function () {},
    126: function () {},
    127: function () {},
    128: function () {},
    129: function () {},
    130: function () {},
    131: function () {},
    132: function () {},
    133: function () {},
    134: function () {},
    135: function () {},
    136: function () {},
    137: function () {},
    138: function () {},
    139: function () {},
    140: function () {},
    141: function () {},
    142: function () {},
    143: function () {},
    144: function () {},
    145: function () {},
    146: function () {},
    147: function () {},
    148: function () {},
    149: function () {},
    150: function () {},
    151: function () {},
    152: function () {},
    153: function () {},
    154: function () {},
    155: function () {},
    156: function () {},
    157: function () {},
    158: function () {},
    159: function () {},
    160: function () {},
    161: function () {},
    162: function () {},
    163: function () {},
    164: function () {},
    165: function () {},
    166: function () {},
    167: function () {},
    168: function () {},
    169: function () {},
    170: function () {},
    171: function () {},
    172: function () {},
    173: function () {},
    174: function () {},
    175: function () {},
    176: function () {},
    177: function () {},
    178: function () {},
    179: function () {},
    180: function () {},
    181: function () {},
    182: function () {},
    183: function () {},
    184: function () {},
    185: function () {},
    186: function () {},
    187: function () {},
    188: function () {},
    189: function () {},
    190: function () {},
    191: function () {},
    192: function () {},
    193: function () {},
    194: function () {},
    195: function () {},
    196: function () {},
    197: function () {},
    198: function () {},
    199: function () {},
    200: function () {},
    201: function () {},
    202: function () {},
    203: function () {},
    204: function () {},
    205: function () {},
    206: function () {},
    207: function () {},
    208: function () {},
    209: function () {},
    210: function () {},
    211: function () {},
    212: function () {},
    213: function () {},
    214: function () {},
    215: function () {},
    216: function () {},
    217: function () {},
    218: function () {},
    219: function () {},
    220: function () {},
    221: function () {},
    222: function () {},
    223: function () {},
    224: function () {},
    225: function () {},
    226: function () {},
    227: function () {},
    228: function () {},
    229: function () {},
    230: function () {},
    231: function () {},
    232: function () {},
    233: function () {},
    234: function () {},
    235: function () {},
    236: function () {},
    237: function () {},
    238: function () {},
    239: function () {},
    240: function () {},
    241: function () {},
    242: function () {},
    243: function () {},
    244: function () {},
    245: function () {},
    246: function () {},
    247: function () {},
    248: function () {},
    249: function () {},
    250: function () {},
    251: function () {},
    252: function () {},
    253: function () {},
    254: function () {},
    255: function () {},
  },
  cbmap: {},
};
